// Module includes
#include "module1_module.h"
#include "module2_module.h"

// PARTITION1 partition configuration schedule window
static PARTITION_CONFIGURATION_SCHEDULE_WINDOW_TYPE PARTITION1_PARTITION_CONFIGURATION_SCHEDULE_WINDOW[1] = {
/*1*/{/*START*/(SYSTEM_TIME_TYPE) 0, /*DURATION*/(SYSTEM_TIME_TYPE) 1000000000, /*PERIOD_START*/(BOOLEAN_TYPE) true } };

// PARTITION1 partition configuration schedule
static PARTITION_CONFIGURATION_SCHEDULE_TYPE PARTITION1_PARTITION_CONFIGURATION_SCHEDULE = {
/*PERIOD*/(SYSTEM_TIME_TYPE) 1000000000,
/*DURATION*/(SYSTEM_TIME_TYPE) 1000000000,
/*SCHEDULE_WINDOW_SIZE*/(SIZE_TYPE) 1,
/*SCHEDULE_WINDOW*/PARTITION1_PARTITION_CONFIGURATION_SCHEDULE_WINDOW };

// Partition configuration
static PARTITION_CONFIGURATION_TYPE MODULE1_MODULE_PARTITION_CONFIGURATION[1] = {

/*PARTITION1 partition*/{
/*EXTERNAL_IDENTIFIER*/(PARTITION_ID_TYPE) 1,
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION1",
/*MAXIMUM_PROCESS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_ERRORSTATUS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SAMPLINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_QUEUINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BUFFER_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BLACKBOARD_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SEMAPHORE_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_EVENT_COUNT*/(SIZE_TYPE) 0,
/*PARTITION_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00223000,
/*PARTITION_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00224000,
/*PARTITION_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_IMAGE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00838000,
/*PARTITION_DATA_IMAGE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00335000,
/*PARTITION_HEAP_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DEFAULTPROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x0022E000,
/*PARTITION_DEFAULTPROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_ERRORHANDLER_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_ERRORHANDLER_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_CONFIGURATION_SCHEDULE*/&PARTITION1_PARTITION_CONFIGURATION_SCHEDULE,
/*PARTITION_CONFIGURATION_HEALTHMONITORING*/(PARTITION_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PROCESS_CONFIGURATION_SIZE*/(SIZE_TYPE) 0,
/*PROCESS_CONFIGURATION*/(PROCESS_CONFIGURATION_TYPE *) null,
/*PORT_PARTITION_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null } };

// Port MODULE1 module configuration
static PORT_MODULE_CONFIGURATION_TYPE MODULE1_PORT_MODULE_CONFIGURATION = {
/*VECTORTABLE_ADDRESS*/(portADDRESS) 0x00000000,
/*VECTORTABLE_SIZE*/(portSIZE) 0x00001000,
/*MODULE_FLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x00438000,
/*MODULE_FLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_SLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x00538000,
/*MODULE_SLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_GLOBAL_FLTRANSLATIONTABLE_ADDRESS (Filled by the operating system)*/(portUINTBASE *) null };

// MODULE1 module configuration
MODULE_CONFIGURATION_TYPE MODULE1_MODULE_CONFIGURATION = {
/*MAXIMUM_PARTITION_COUNT*/(SIZE_TYPE) 1,
/*MODULE_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x0022A000,
/*MODULE_STACK_SIZE*/(SIZE_TYPE) 0x00004000,
/*MODULE_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00221000,
/*MODULE_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00222000,
/*MODULE_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00235000,
/*MODULE_HEAP_SIZE*/(SIZE_TYPE) 0x00100000,
/*MODULE_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*MODULE_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*MAJORFRAME_DURATION*/(SYSTEM_TIME_TYPE) 1000000000,
/*MODULE_CONFIGURATION_CONNECTIONTABLE*/(MODULE_CONFIGURATION_CONNECTIONTABLE_TYPE *) null,
/*MODULE_CONFIGURATION_HEALTHMONITORING*/(MODULE_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PARTITION_CONFIGURATION_SIZE*/(SIZE_TYPE) 1,
/*PARTITION_CONFIGURATION*/MODULE1_MODULE_PARTITION_CONFIGURATION,
/*PORT_MODULE_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) &MODULE1_PORT_MODULE_CONFIGURATION };

// PARTITION2 partition configuration schedule window
static PARTITION_CONFIGURATION_SCHEDULE_WINDOW_TYPE PARTITION2_PARTITION_CONFIGURATION_SCHEDULE_WINDOW[1] = {
/*1*/{/*START*/(SYSTEM_TIME_TYPE) 0, /*DURATION*/(SYSTEM_TIME_TYPE) 1000000000, /*PERIOD_START*/(BOOLEAN_TYPE) true } };

// PARTITION2 partition configuration schedule
static PARTITION_CONFIGURATION_SCHEDULE_TYPE PARTITION2_PARTITION_CONFIGURATION_SCHEDULE = {
/*PERIOD*/(SYSTEM_TIME_TYPE) 1000000000,
/*DURATION*/(SYSTEM_TIME_TYPE) 1000000000,
/*SCHEDULE_WINDOW_SIZE*/(SIZE_TYPE) 1,
/*SCHEDULE_WINDOW*/PARTITION2_PARTITION_CONFIGURATION_SCHEDULE_WINDOW };

// Partition configuration
static PARTITION_CONFIGURATION_TYPE MODULE2_MODULE_PARTITION_CONFIGURATION[1] = {

/*PARTITION2 partition*/{
/*EXTERNAL_IDENTIFIER*/(PARTITION_ID_TYPE) 2,
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION2",
/*MAXIMUM_PROCESS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_ERRORSTATUS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SAMPLINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_QUEUINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BUFFER_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BLACKBOARD_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SEMAPHORE_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_EVENT_COUNT*/(SIZE_TYPE) 0,
/*PARTITION_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00227000,
/*PARTITION_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00228000,
/*PARTITION_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_IMAGE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00839000,
/*PARTITION_DATA_IMAGE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00436000,
/*PARTITION_HEAP_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DEFAULTPROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00233000,
/*PARTITION_DEFAULTPROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_ERRORHANDLER_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_ERRORHANDLER_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_CONFIGURATION_SCHEDULE*/&PARTITION2_PARTITION_CONFIGURATION_SCHEDULE,
/*PARTITION_CONFIGURATION_HEALTHMONITORING*/(PARTITION_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PROCESS_CONFIGURATION_SIZE*/(SIZE_TYPE) 0,
/*PROCESS_CONFIGURATION*/(PROCESS_CONFIGURATION_TYPE *) null,
/*PORT_PARTITION_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null } };

// Port MODULE2 module configuration
static PORT_MODULE_CONFIGURATION_TYPE MODULE2_PORT_MODULE_CONFIGURATION = {
/*VECTORTABLE_ADDRESS*/(portADDRESS) 0x00001000,
/*VECTORTABLE_SIZE*/(portSIZE) 0x00001000,
/*MODULE_FLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x00638000,
/*MODULE_FLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_SLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x00738000,
/*MODULE_SLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_GLOBAL_FLTRANSLATIONTABLE_ADDRESS (Filled by the operating system)*/(portUINTBASE *) null };

// MODULE2 module configuration
MODULE_CONFIGURATION_TYPE MODULE2_MODULE_CONFIGURATION = {
/*MAXIMUM_PARTITION_COUNT*/(SIZE_TYPE) 1,
/*MODULE_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x0022F000,
/*MODULE_STACK_SIZE*/(SIZE_TYPE) 0x00004000,
/*MODULE_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00225000,
/*MODULE_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00226000,
/*MODULE_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00336000,
/*MODULE_HEAP_SIZE*/(SIZE_TYPE) 0x00100000,
/*MODULE_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*MODULE_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*MAJORFRAME_DURATION*/(SYSTEM_TIME_TYPE) 1000000000,
/*MODULE_CONFIGURATION_CONNECTIONTABLE*/(MODULE_CONFIGURATION_CONNECTIONTABLE_TYPE *) null,
/*MODULE_CONFIGURATION_HEALTHMONITORING*/(MODULE_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PARTITION_CONFIGURATION_SIZE*/(SIZE_TYPE) 1,
/*PARTITION_CONFIGURATION*/MODULE2_MODULE_PARTITION_CONFIGURATION,
/*PORT_MODULE_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) &MODULE2_PORT_MODULE_CONFIGURATION };

// Port system configuration
static PORT_SYSTEM_CONFIGURATION_TYPE PORT_SYSTEM_CONFIGURATION = {
/*STACK_AREA_START_ADDRESS*/(portADDRESS) 0x00229000,
/*STACK_AREA_END_ADDRESS*/(portADDRESS) 0x00235000,
/*PERIPHERALS_ADDRESS*/(portADDRESS) 0x40000000,
/*PERIPHERALS_SIZE*/(portSIZE) 0xC0000000,
/*SYSTEM_BOOT_ADDRESS*/(portADDRESS) 0x00100000,
/*SYSTEM_BOOT_SIZE*/(portSIZE) 0x00001000 };

// System configuration
SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION = {
/*SYSTEM_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00101000,
/*SYSTEM_CODE_SIZE*/(SIZE_TYPE) 0x00020000,
/*SYSTEM_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x00121000,
/*SYSTEM_DATA_SIZE*/(SIZE_TYPE) 0x00100000,
/*SYSTEM_CONFIGURATION_HEALTHMONITORING*/(SYSTEM_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PORT_SYSTEM_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) &PORT_SYSTEM_CONFIGURATION };
