#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

// System configuration
extern SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION;

// MODULE1 module configuration
extern MODULE_CONFIGURATION_TYPE MODULE1_MODULE_CONFIGURATION;

// MODULE2 module configuration
extern MODULE_CONFIGURATION_TYPE MODULE2_MODULE_CONFIGURATION;

#endif
